# Generated by Django 4.0.6 on 2024-04-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('objetivos', models.TextField()),
                ('competencias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinguagemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tecnologiasUsadas', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='curso/')),
                ('linkYoutube', models.URLField(blank=True, null=True)),
                ('linkGithub', models.URLField(blank=True, null=True)),
                ('conceitosAplicados', models.ManyToManyField(to='curso.projeto')),
                ('linguagensProgramacao', models.ManyToManyField(to='curso.linguagemprogramacao')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('curricularUnitReadableCode', models.CharField(max_length=255)),
                ('areaCientifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='curso.areacientifica')),
                ('linguagensProgramacao', models.ManyToManyField(to='curso.linguagemprogramacao')),
                ('projeto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.projeto')),
            ],
        ),
    ]
