# Generated by Django 4.0.6 on 2024-06-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_disciplina_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
    ]
