# Generated by Django 4.0.6 on 2024-06-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_alter_disciplina_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='conceitosAplicados',
        ),
        migrations.AddField(
            model_name='projeto',
            name='conceitosAplicados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
