# Generated by Django 4.0.6 on 2024-06-04 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_remove_projeto_conceitosaplicados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='curso.curso'),
        ),
    ]
