# Generated by Django 4.0.6 on 2024-06-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0009_alter_disciplina_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='linguagensProgramacao',
            field=models.ManyToManyField(blank=True, null=True, to='curso.linguagemprogramacao'),
        ),
    ]
