# Generated by Django 4.0.6 on 2024-06-07 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0012_projeto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='curso.disciplina'),
        ),
    ]
