# Generated by Django 4.0.6 on 2024-06-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0013_alter_projeto_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='linguagensProgramacao',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplina', to='curso.linguagemprogramacao'),
        ),
    ]
