# Generated by Django 4.0.6 on 2024-06-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0014_alter_disciplina_linguagensprogramacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='linguagensProgramacao',
            field=models.ManyToManyField(related_name='projetos', to='curso.linguagemprogramacao'),
        ),
    ]
