# Generated by Django 4.0.6 on 2024-06-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_band_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='imgs'),
        ),
    ]
