# Generated by Django 4.0.6 on 2024-06-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_alter_album_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
