# Generated by Django 4.0.6 on 2024-06-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_alter_band_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='letra',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
