# Generated by Django 4.0.6 on 2024-06-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_song_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='biografia',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
