# Generated by Django 4.0.6 on 2024-06-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_song_biografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='biografia',
        ),
        migrations.AddField(
            model_name='band',
            name='biografia',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
